version: "3.9"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: sh -lc "mvn install && mvn test -DsuiteXmlFile=testng.xml"
    # If you need interactive debugging:
    tty: true
    stdin_open: true
